from twisted.internet import reactor, defer
from scrapy.crawler import CrawlerRunner
from scrapy.utils.log import configure_logging
from scrapy.utils.project import get_project_settings

configure_logging()
runner = CrawlerRunner(get_project_settings())

@defer.inlineCallbacks
def crawl():
	yield runner.crawl('godaddy', base_url='https://foggymoose.ca/', vendor_id=62, api_url='https://80955219-8b23-4c20-ae1f-46841f836fba.mysimplestore.com/')

	yield runner.crawl('volusion', base_url='https://www.digitalimports.ca/', vendor_id=24)
	yield runner.crawl('volusion', base_url='https://www.diy-ejuice.com/', vendor_id=27)
	yield runner.crawl('volusion', base_url='https://www.thebrewtimevaper.com/', vendor_id=28)
	yield runner.crawl('volusion', base_url='https://www.eastcoastvape.ca/', vendor_id=38)

	yield runner.crawl('shopify', base_url='https://ecigarettes.ca/', vendor_id=2)
	yield runner.crawl('shopify', base_url='https://flavorificshop.com/', vendor_id=3)
	yield runner.crawl('shopify', base_url='https://evaperated.com/', vendor_id=4)
	yield runner.crawl('shopify', base_url='https://emixologies.com/', vendor_id=5)
	yield runner.crawl('shopify', base_url='https://bargainejuice.ca/', vendor_id=7)
	yield runner.crawl('shopify', base_url='https://libertyvape.ca/', vendor_id=9)
	yield runner.crawl('shopify', base_url='https://sagavape.com/', vendor_id=10)
	yield runner.crawl('shopify', base_url='https://dragonvape.ca/', vendor_id=11)
	yield runner.crawl('shopify', base_url='https://saddlehorseblues.com/', vendor_id=12)
	yield runner.crawl('shopify', base_url='https://qpdesign.ca/', vendor_id=13)
	yield runner.crawl('shopify', base_url='https://nyxecigs.com/', vendor_id=14)
	yield runner.crawl('shopify', base_url='https://gascityvapes.com/', vendor_id=15)
	yield runner.crawl('shopify', base_url='https://coolvape.ca/', vendor_id=16)
	yield runner.crawl('shopify', base_url='https://fatpanda.ca/', vendor_id=17)
	yield runner.crawl('shopify', base_url='https://rivercityvapes.com/', vendor_id=18)
	yield runner.crawl('shopify', base_url='https://truenorthvapor.com/', vendor_id=19)
	yield runner.crawl('shopify', base_url='https://thevillagevaporette.com/', vendor_id=20)
	yield runner.crawl('shopify', base_url='https://vapemeet.ca/', vendor_id=21)
	yield runner.crawl('shopify', base_url='https://steepedmonkeybrains.com/', vendor_id=22)
	yield runner.crawl('shopify', base_url='https://vjuice.ca/', vendor_id=25)
	yield runner.crawl('shopify', base_url='https://carrackvape.com/', vendor_id=26)
	yield runner.crawl('shopify', base_url='https://coldturkeyjuice.com/', vendor_id=29)
	yield runner.crawl('shopify', base_url='https://thevapory.com/', vendor_id=30)
	yield runner.crawl('shopify', base_url='https://vaporjunkie.ca/', vendor_id=31)
	yield runner.crawl('shopify', base_url='https://sopunvapeshop.com/', vendor_id=32)
	yield runner.crawl('shopify', base_url='https://vapourscanada.com/', vendor_id=40)
	yield runner.crawl('shopify', base_url='https://recordvapes.com/', vendor_id=42)
	yield runner.crawl('shopify', base_url='https://truenorthern.ca/', vendor_id=44)
	yield runner.crawl('shopify', base_url='https://vape360.ca/', vendor_id=45)
	yield runner.crawl('shopify', base_url='https://vapecity.ca/', vendor_id=47)
	yield runner.crawl('shopify', base_url='https://thevapebunker.ca/', vendor_id=48)
	yield runner.crawl('shopify', base_url='https://18650canada.com/', vendor_id=53)
	yield runner.crawl('shopify', base_url='https://vapingjill.com/', vendor_id=54)
	yield runner.crawl('shopify', base_url='https://hazevapeco.com/', vendor_id=55)
	yield runner.crawl('shopify', base_url='https://hotshotsvapor.ca/', vendor_id=56)
	yield runner.crawl('shopify', base_url='https://cyruseliquid.com/', vendor_id=57)
	yield runner.crawl('shopify', base_url='https://vapornorth.com/', vendor_id=58)
	yield runner.crawl('shopify', base_url='https://bayvape.ca/', vendor_id=59)
	yield runner.crawl('shopify', base_url='https://vapecave.ca/', vendor_id=61)
	yield runner.crawl('shopify', base_url='https://ontariovape.com/', vendor_id=66)
	yield runner.crawl('shopify', base_url='https://bullfrogvape.com/', vendor_id=67)
	yield runner.crawl('shopify', base_url='https://alldayvapes.ca/', vendor_id=68)
	yield runner.crawl('shopify', base_url='https://thevapeclub.ca/', vendor_id=70)
	yield runner.crawl('shopify', base_url='https://mysticvapor.ca/', vendor_id=72)
	yield runner.crawl('shopify', base_url='https://shop.vapestreetcanada.com/', vendor_id=73)
	yield runner.crawl('shopify', base_url='https://canvape.com/', vendor_id=23)
	yield runner.crawl('shopify', base_url='https://www.rivercityvapes.com/', vendor_id=18)
	yield runner.crawl('shopify', base_url='https://theravape.net/', vendor_id=75)
	yield runner.crawl('shopify', base_url='https://www.vapewave.ca/', vendor_id=76)
	yield runner.crawl('shopify', base_url='https://bulkejuicecanada.com/', vendor_id=77)

	yield runner.crawl('wordpress', base_url='https://acevaper.ca/', vendor_id=34)
	yield runner.crawl('wordpress', base_url='https://vapevine.ca/', vendor_id=35)
	yield runner.crawl('wordpress', base_url='https://vapourchoice.ca/', vendor_id=41)
	yield runner.crawl('wordpress', base_url='https://vapedensity.ca/', vendor_id=43)
	yield runner.crawl('wordpress', base_url='https://thebrokevaper.ca/', vendor_id=46)
	yield runner.crawl('wordpress', base_url='https://liquidejuice.com/', vendor_id=49)
	yield runner.crawl('wordpress', base_url='https://infuzion.ca/', vendor_id=51)
	yield runner.crawl('wordpress', base_url='https://ejuices.ca/', vendor_id=52)
	yield runner.crawl('wordpress', base_url='https://canadavapes.com/', vendor_id=64)
	yield runner.crawl('wordpress', base_url='https://vapeloft.com/', vendor_id=69)
	yield runner.crawl('wordpress', base_url='https://vapeme.net/', vendor_id=71)
	# Disabled because images are forbidden
	# yield runner.crawl('wordpress', base_url='https://jeancloudvape.com/', vendor_id=74)

	yield runner.crawl('dashvapes')

	yield runner.crawl('lightspeed', base_url='https://www.flamingoplus.ca/', vendor_id=60)

	reactor.stop()

crawl()
reactor.run()